version: '3.1'

services:
  app:
    build: .
#    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cloud_vendor
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Trongtin123@
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Trongtin123@
      MYSQL_DATABASE: cloud_vendor
    ports:
      - "3300:3306"
    volumes:
      - ./mysql:/var/lib/mysql


